import 'package:clackbox/constants/app_color_scheme.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:google_fonts/google_fonts.dart';

final lightTextTheme = TextTheme(
  displayLarge: GoogleFonts.plusJakartaSans(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 48.sp,
    fontWeight: FontWeight.w700,
    letterSpacing: 0.5,
    height: 1.2,
  ),
  displayMedium: GoogleFonts.plusJakartaSans(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 36,
    fontWeight: FontWeight.w700,
    letterSpacing: 0.5,
    height: 1.2,
  ),
  // displaySmall: TextStyle(
  //   color: Color(lightColorScheme.onBackground.value),
  //   fontSize: 24,
  //   fontWeight: FontWeight.w700,
  //   letterSpacing: 0.5,
  //   height: 1.2,
  // ),
  displaySmall: GoogleFonts.plusJakartaSans(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 24,
    fontWeight: FontWeight.w700,
    letterSpacing: 0.5,
    height: 1.2,
  ),

  headlineLarge: GoogleFonts.plusJakartaSans(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 20,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  headlineMedium: GoogleFonts.plusJakartaSans(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 16,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  headlineSmall: GoogleFonts.plusJakartaSans(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 14,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  titleLarge: GoogleFonts.plusJakartaSans(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 20,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  titleMedium: GoogleFonts.plusJakartaSans(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 16,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  titleSmall: GoogleFonts.plusJakartaSans(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 14,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  bodyLarge: GoogleFonts.plusJakartaSans(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 20,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  bodyMedium: GoogleFonts.plusJakartaSans(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 16,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  bodySmall: GoogleFonts.plusJakartaSans(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 14,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  labelLarge: GoogleFonts.plusJakartaSans(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 20,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  labelMedium: GoogleFonts.plusJakartaSans(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 16,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  labelSmall: GoogleFonts.plusJakartaSans(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 14,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
    height: 1.2,
  ),
);

final darkTextTheme = TextTheme(
  displayLarge: GoogleFonts.plusJakartaSans(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 48,
    fontWeight: FontWeight.w700,
    letterSpacing: 0.5,
    height: 1.2,
  ),
  displayMedium: GoogleFonts.plusJakartaSans(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 36,
    fontWeight: FontWeight.w700,
    letterSpacing: 0.5,
    height: 1.2,
  ),
  displaySmall: GoogleFonts.plusJakartaSans(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 24,
    fontWeight: FontWeight.w700,
    letterSpacing: 0.5,
    height: 1.2,
  ),
  headlineLarge: GoogleFonts.plusJakartaSans(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 20,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  headlineMedium: GoogleFonts.plusJakartaSans(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 16,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  headlineSmall: GoogleFonts.plusJakartaSans(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 14,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  titleLarge: GoogleFonts.plusJakartaSans(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 20,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  titleMedium: GoogleFonts.plusJakartaSans(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 16,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  titleSmall: GoogleFonts.plusJakartaSans(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 14,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  bodyLarge: GoogleFonts.plusJakartaSans(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 20,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  bodyMedium: GoogleFonts.plusJakartaSans(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 16,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  bodySmall: GoogleFonts.plusJakartaSans(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 14,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  labelLarge: GoogleFonts.plusJakartaSans(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 20,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  labelMedium: GoogleFonts.plusJakartaSans(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 16,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  labelSmall: GoogleFonts.plusJakartaSans(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 14,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
    height: 1.2,
  ),
);
