import 'package:clackbox/common/constants/app_color_scheme.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

final lightTextTheme = TextTheme(
  displayLarge: TextStyle(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 48.sp,
    fontWeight: FontWeight.w700,
    letterSpacing: 0.5,
    height: 1.2,
  ),
  displayMedium: TextStyle(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 36,
    fontWeight: FontWeight.w700,
    letterSpacing: 0.5,
    height: 1.2,
  ),
  displaySmall: TextStyle(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 24,
    fontWeight: FontWeight.w700,
    letterSpacing: 0.5,
    height: 1.2,
  ),
  headlineLarge: TextStyle(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 20,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  headlineMedium: TextStyle(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 16,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  headlineSmall: TextStyle(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 14,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  titleLarge: TextStyle(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 20,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  titleMedium: TextStyle(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 16,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  titleSmall: TextStyle(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 14,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  bodyLarge: TextStyle(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 20,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  bodyMedium: TextStyle(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 16,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  bodySmall: TextStyle(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 14,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  labelLarge: TextStyle(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 20,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  labelMedium: TextStyle(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 16,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  labelSmall: TextStyle(
    color: Color(lightColorScheme.onBackground.value),
    fontSize: 14,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
    height: 1.2,
  ),
);

final darkTextTheme = TextTheme(
  displayLarge: TextStyle(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 48,
    fontWeight: FontWeight.w700,
    letterSpacing: 0.5,
    height: 1.2,
  ),
  displayMedium: TextStyle(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 36,
    fontWeight: FontWeight.w700,
    letterSpacing: 0.5,
    height: 1.2,
  ),
  displaySmall: TextStyle(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 24,
    fontWeight: FontWeight.w700,
    letterSpacing: 0.5,
    height: 1.2,
  ),
  headlineLarge: TextStyle(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 20,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  headlineMedium: TextStyle(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 16,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  headlineSmall: TextStyle(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 14,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  titleLarge: TextStyle(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 20,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  titleMedium: TextStyle(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 16,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  titleSmall: TextStyle(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 14,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
    height: 1.2,
  ),
  bodyLarge: TextStyle(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 20,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  bodyMedium: TextStyle(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 16,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  bodySmall: TextStyle(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 14,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  labelLarge: TextStyle(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 20,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  labelMedium: TextStyle(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 16,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
    height: 1.2,
  ),
  labelSmall: TextStyle(
    color: Color(darkColorScheme.onBackground.value),
    fontSize: 14,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
    height: 1.2,
  ),
);
